insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Ann Smith', '123 address', 'email2@gmail.com', 'password', '0987654321');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Bob Brown', '456 address', 'email3@gmail.com', 'password', '2345678901');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Joe Bruin', '789 address', 'email1@gmail.com', 'password', '0123456789');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('ADMIN', 'Frank F', '321 address', 'email@ucla.edu', 'password', '1234567890');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Charlie C', '654 address', 'email5@gmail.edu', 'password', '1234567890');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Dave D', '987 address', 'email6@gmail.edu', 'password', '6666666666');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Ethan E', '231 address', 'email9@gmail.edu', 'password', '9999999999');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Groot G', '564 address', 'email7@gmail.edu', 'password', '7777777777');
insert into `user` (`userType`, `name`, `address`, `email`, `password`, `cardNumber`) values ('USER', 'Hadoop H', '897 address', 'email0@gmail.edu', 'password', '0000000000');